#!/bin/bash

if [ $# -eq 0 ]
then
        echo Usage: phone searchfor \[...searchfor\]
        echo \(You didn\'t tell me what you want to search for.\)
else
        arg=\($*\)
        egrep -i ${arg//' '/'|'} mydata | awk -f display.awk
fi

